### ISSUE TITLE
"past_key_value" and "cache_position" key changes in recent versions of transformers

### ISSUE THREAD

**Issue by jblamare** [adapter-hub/adapters#824]
## Environment info

- `adapters` version: 1.2.0
- `transformers` version: 4.56.1
- Platform: Linux-5.15.0-91-generic-x86_64-with-glibc2.35
- Python version: 3.12.8
- PyTorch version (accelerator?): 2.7.1+cu126 (CUDA)
- Tensorflow version (GPU?): 2.20.0 (True)
- Using distributed or parallel set-up in script?: No
- Using GPU in script?: Yes

## Information

Model I am using (Bert, XLNet ...): Bert

Language I am using the model on (English, Chinese ...): English

Adapter setup I am using (if any): any 

The problem arises when using:
* [x] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

## To reproduce

```
import adapters
from transformers import AutoTokenizer, AutoModelForSequenceClassification

tokenizer = AutoTokenizer.from_pretrained("google-bert/bert-base-uncased")
model = AutoModelForSequenceClassification.from_pretrained("google-bert/bert-base-uncased")
adapters.init(model)
model.add_adapter("my_lora_adapter", config="lora")
print(model(**tokenizer("This works great!", return_tensors="pt")).logits)
```

```
TypeError: BertSdpaSelfAttentionWithAdapters.forward() got an unexpected keyword argument 'past_key_values'
```

## Expected behavior

For the above to work with transformers>=4.56.0.

When transformers was upgraded from [4.53.3](https://github.com/huggingface/transformers/blob/v4.53.3/src/transformers/models/bert/modeling_bert.py#L553) to [4.54.0](https://github.com/huggingface/transformers/blob/v4.54.0/src/transformers/models/bert/modeling_bert.py#L590), a new `cache_position` key was added as argument to the attention forward method.
Similarly, when transformers was upgraded from [4.55.4](https://github.com/huggingface/transformers/blob/v4.55.4/src/transformers/models/bert/modeling_bert.py#L567) to [4.56.0](https://github.com/huggingface/transformers/blob/v4.56.0/src/transformers/models/bert/modeling_bert.py#L562), the `past_key_value` key was renamed to `past_key_values`.

The [current version of adapters](https://github.com/adapter-hub/adapters/blob/v1.2.0/src/adapters/models/bert/modeling_bert.py#L150) doesn't handle these two changes. For `past_key_values`, I think it's a simple search & replace with `past_key_values`. For `cache_position`, I'm not sure how much should be updated. Also the above is for Bert, but it might apply to other models.
